---
 - hosts: localhost
   become: sudo
   tasks:
     - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
       ansible.builtin.include_vars:
       dir: vars/all
       extensions: .txt
     - name: copying the config file to server
       copy:
           src: nginx.conf
           dest: /etc/nginx/nginx.conf
           owner: root
           group: root
           mode: 0644
           
     - name: Restart nginx
       service: name=nginx state=restarted
