---
 - hosts: nodes
   become: sudo
   tasks:
     - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
       ansible.builtin.include_vars:
         dir: /var/lib/jenkins/workspace/auto_trigger_job/ 
         extensions: .conf
     - name: copying the config file to server
       copy:
           src: /var/lib/jenkins/workspace/auto_trigger_job/
           dest: /etc/nginx/nginx.conf
           owner: root
           group: root
           mode: 0644
           
     - name: Restart nginx
       service: name=nginx state=restarted
