---
 - hosts: nodes
   become: sudo
   vars:
       item: output.txt
   tasks:
   
     - name: printing modified files
       shell: "cd jenkins_demo && git diff --name-only HEAD^..| sudo tee output.txt"
       become: true 
       
     - name: Copy each file over that matches the given pattern
       copy:
        src: "{{ item }}"
        dest: "/etc/nginx/nginx.conf"
        owner: "root"
        mode: 600
       with_fileglob:
        - "/jenkins_demo/*"
           
     - name: Restart nginx
       service: 
          name: nginx 
          state: restarted
