---
 - hosts: nodes
   become: sudo
   vars:
    source: "{{ source }}"
    destination: "{{ destination }}"
   tasks:
     - name: copying the config file to server
       copy:
           src: "{{ source }}"
           dest:"{{ destination }}"
           owner: root
           group: root
           mode: 0644
           
     - name: Restart nginx
       service: name=nginx state=restarted
