---
 - hosts: nodes
   become: sudo
   
     - name: printing modified files
       shell: sh "cd jenkins_demo | git diff --name-only HEAD^.. | tee output.txt"
       
     - name: copying the config file to server
       copy:
           src: "{{ source }}"
           dest: "{{ destination }}"
           owner: root
           group: root
           mode: 0644
           
     - name: Restart nginx
       service: name=nginx state=restarted
