---
 - hosts: nodes
   tasks:
       
     - name: copying the config file to server
       copy:
           src: /etc/nginx/nginx.conf
           dest: /home/ec2-user
           owner: root
           group: root
           mode: 0644
