---
 - hosts: all
   tasks:
   
     - name: Copy each file over that matches the given pattern
       copy:
        src = "{{src}}"
        dest= "{{dest}}"
           
     - name: Restart service
       ansible.builtin.service:
          name: "{{service}}"
          state: restarted
