---
 - hosts: nodes
   become: sudo
   
     - name: printing modified files
       ansible.builtin.shell: cd jenkins_demo
       become: true 
       
     - name: copying the config file to server
       copy:
           src: "{{ source }}"
           dest: "{{ destination }}"
           owner: root
           group: root
           mode: 0644
           
     - name: Restart nginx
       service: name=nginx state=restarted
